Added a hack of restarting 'httpd' allows Pulp to function. Seeing exception: I'm seeing this on a fresh install of a Fedora 20 VM. Note, if I run "systemctl restart httpd" Pulp is happy and I'm able to login and create/sync a repo. It's the initial run of 'httpd' and the celery workers which is triggering the below.
Mar 25 14:13:13 localhost pulp: pulp.server.webservices.application:INFO: *************************************************************
Mar 25 14:13:13 localhost pulp: pulp.server.webservices.application:INFO: The Pulp server has been successfully initialized
Mar 25 14:13:13 localhost pulp: pulp.server.webservices.application:INFO: *************************************************************
Mar 25 14:13:13 localhost kernel: [  200.368118] httpd[2788]: segfault at 58 ip 00007fc73f9d4797 sp 00007fc7332316c0 error 4 in libpython2.7.so.1.0[7fc73f8f5000+178000]
Mar 25 14:13:13 localhost kernel: httpd[2788]: segfault at 58 ip 00007fc73f9d4797 sp 00007fc7332316c0 error 4 in libpython2.7.so.1.0[7fc73f8f5000+178000]
Mar 25 14:13:13 localhost pulp: pulp.server.webservices.application:CRITICAL: *************************************************************
Mar 25 14:13:13 localhost pulp: pulp.server.webservices.application:ERROR: The Pulp server encountered an unexpected failure during initialization
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pulp/server/webservices/application.py", line 151, in wsgi_application
    _initialize_pulp()
  File "/usr/lib/python2.7/site-packages/pulp/server/webservices/application.py", line 115, in _initialize_pulp
    user_manager.ensure_admin()
  File "/usr/lib/python2.7/site-packages/pulp/server/managers/auth/user/cud.py", line 214, in ensure_admin
    password=default_password)
  File "/usr/lib/python2.7/site-packages/pulp/server/managers/auth/user/cud.py", line 88, in create_user
    User.get_collection().save(create_me, safe=True)
  File "/usr/lib/python2.7/site-packages/pulp/server/db/connection.py", line 135, in retry
    return method(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 269, in save
    manipulate, safe, check_keys=check_keys, **kwargs)
  File "/usr/lib/python2.7/site-packages/pulp/server/db/connection.py", line 135, in retry
    return method(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 479, in update
    check_keys, self.__uuid_subtype), safe)
  File "/usr/lib/python2.7/site-packages/pulp/server/db/connection.py", line 166, in _with_end_request
    return method(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 920, in _send_message
    rv = self.__check_response_to_last_error(response)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 861, in __check_response_to_last_error
    raise DuplicateKeyError(details["err"], details["code"])
DuplicateKeyError: E11000 duplicate key error index: pulp_database.users.$login_-1  dup key: { : "admin" }